aerobridge/urls.py
from django.contrib import admin
from django.urls import include, path



from django.conf import settings
from django.conf.urls.static import static
import jetway.views as jetwayviews

urlpatterns = [
    
    path('ping/', jetwayviews.PingView.as_view(), name="ping"),
    path('', jetwayviews.HomeView.as_view()),
    path('admin/', admin.site.urls),

    path('launchpad/', include('launchpad.urls')),
    path('pki/', include('pki_framework.urls')),
    path('gcs/', include('gcs_operations.urls')),
    path('registry/', include('registry.urls')),
    # YOUR PATTERNS
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns = format_suffix_patterns(urlpatterns)

launchpad/urls.py
from django.urls import path, re_path
from . import views as launchpad_views

urlpatterns = [
    path('', launchpad_views.HomeView.as_view()),
    path('addresses', launchpad_views.AddressList.as_view(), name='addresses-list'),
    path('addresses/<uuid:address_id>', launchpad_views.AddressDetail.as_view(), name='addresses-detail'),
    path('addresses/new', launchpad_views.AddressCreateView.as_view(), name='addresses-create'),

    path('people', launchpad_views.PeopleList.as_view(), name='people-list'),
    path('people/<uuid:person_id>', launchpad_views.PersonUpdate.as_view(), name='people-update'),
    path('people/<uuid:person_id>/detail', launchpad_views.PersonDetail.as_view(), name='people-detail'),
    path('people/new', launchpad_views.PersonCreateView.as_view(), name='people-create'),
 
    path('operators', launchpad_views.OperatorList.as_view(), name='operators-list'),
    path('operators/<uuid:operator_id>', launchpad_views.OperatorUpdate.as_view(), name='operators-update'),
    path('operators/<uuid:operator_id>/detail', launchpad_views.OperatorDetail.as_view(), name='operators-detail'),
    path('operators/new', launchpad_views.OperatorCreateView.as_view(), name='operators-create'),

    path('contacts', launchpad_views.ContactsList.as_view(), name='contacts-list'),
    path('contacts/<uuid:contact_id>', launchpad_views.ContactsUpdate.as_view(), name='contacts-update'),
    path('contacts/<uuid:contact_id>/detail', launchpad_views.ContactsDetail.as_view(), name='contacts-detail'),
    path('contacts/new', launchpad_views.ContactsCreateView.as_view(), name='contacts-create'),
 
    path('pilots', launchpad_views.PilotsList.as_view(), name='pilots-list'),
    path('pilots/<uuid:pilot_id>', launchpad_views.PilotsUpdate.as_view(), name='pilots-update'),
    path('pilots/<uuid:pilot_id>/detail', launchpad_views.PilotsDetail.as_view(), name='pilots-detail'),
    path('pilots/new', launchpad_views.PilotsCreateView.as_view(), name='pilots-create'),
     
    path('activities', launchpad_views.ActivitiesList.as_view(), name='activities-list'),
    path('activities/<uuid:activity_id>', launchpad_views.ActivitiesUpdate.as_view(), name='activities-update'),
    path('activities/<uuid:activity_id>/detail', launchpad_views.ActivitiesDetail.as_view(), name='activities-detail'),
    path('activities/new', launchpad_views.ActivitiesCreateView.as_view(), name='activities-create'),
     
    path('authorizations', launchpad_views.AuthorizationsList.as_view(), name='authorizations-list'),
    path('authorizations/<uuid:authorization_id>', launchpad_views.AuthorizationsUpdate.as_view(), name='authorizations-update'),
    path('authorizations/<uuid:authorization_id>/detail', launchpad_views.AuthorizationsDetail.as_view(), name='authorizations-detail'),
    path('authorizations/new', launchpad_views.AuthorizationsCreateView.as_view(), name='authorizations-create'),
     
    path('aircrafts', launchpad_views.AircraftList.as_view(), name='aircrafts-list'),
    path('aircrafts/<uuid:aircraft_id>', launchpad_views.AircraftUpdate.as_view(), name='aircrafts-update'),
    path('aircrafts/<uuid:aircraft_id>/detail', launchpad_views.AircraftDetail.as_view()), 
    path('aircrafts/<uuid:aircraft_id>/components', launchpad_views.AircraftComponents.as_view(), name='aircrafts-detail'),
    path('aircrafts/new', launchpad_views.AircraftCreateView.as_view(), name='aircrafts-create'),

    path('aircraft-extended', launchpad_views.AircraftExtendedList.as_view(), name='aircraft-extended-list'),
    path('aircraft-extended/<uuid:aircraft_detail_id>', launchpad_views.AircraftExtendedUpdate.as_view(), name='aircraft-extended-update'),
    path('aircraft-extended/<uuid:aircraft_detail_id>/detail', launchpad_views.AircraftExtendedDetail.as_view(), name='aircraft-extended-detail'),
    path('aircraft-extended/new', launchpad_views.AircraftExtendedCreateView.as_view(), name='aircraft-extended-create'),
 
    path('manufacturing-read-first', launchpad_views.ManufacturingReadFirst.as_view(), name='manufacturing-read-first'),
     
    path('aircraft-models', launchpad_views.AircraftModelsList.as_view(), name='aircraft-models-list'),
    path('aircraft-models/<uuid:aircraft_model_id>', launchpad_views.AircraftModelsUpdate.as_view(), name='aircraft-models-update'),
    path('aircraft-models/<uuid:aircraft_model_id>/detail', launchpad_views.AircraftModelsDetail.as_view(), name='aircraft-models-detail'),
    path('aircraft-models/new', launchpad_views.AircraftModelsCreateView.as_view(), name='aircraft-models-create'),
    path('aircraft-models/<uuid:aircraft_model_id>/master-components', launchpad_views.AircraftModelMasterComponents.as_view(), name='aircraft-models-detail'),
 
    path('aircraft-assemblies/<uuid:aircraft_model_id>/new', launchpad_views.AircraftAssembliesCreateView.as_view(), name='aircraft-assemblies-create'),
    path('aircraft-assemblies/<uuid:aircraft_assembly_id>/update', launchpad_views.AircraftAssembliesComponentsUpdate.as_view(), name='aircraft-assemblies-components-update'),
    path('aircraft-assemblies/<uuid:aircraft_assembly_id>/detail', launchpad_views.AircraftAssembliesDetail.as_view(), name='aircraft-assemblies-detail'),
    # path('aircraft-assemblies/<uuid:aircraft_assembly_id>', launchpad_views.AircraftAssembliesUpdate.as_view(), name='aircraft-assemblies-update'),
    path('aircraft-assemblies/<str:view_type>', launchpad_views.AircraftAssembliesList.as_view(), name='aircraft-assemblies-list'),
    path('aircraft-assemblies', launchpad_views.AircraftAssembliesList.as_view(), name='aircraft-assemblies-list'),
    
    path('incidents/<uuid:aircraft_id>/new', launchpad_views.IncidentsCreateView.as_view(), name='incidents-create'),    
    path('incidents/calendar', launchpad_views.IncidentsCalendar.as_view(), name='incidents-calendar'),
    path('incidents/<uuid:incident_id>', launchpad_views.IncidentsUpdate.as_view(), name='incidents-update'),
    path('incidents/<uuid:incident_id>/detail', launchpad_views.IncidentsDetail.as_view(), name='incidents-detail'),    
    path('incidents', launchpad_views.IncidentsList.as_view(), name='incidents-list'),
    
  
    path('aircraft-master-components', launchpad_views.AircraftMasterComponentsList.as_view(), name='aircraft-master-components-list'),
    path('aircraft-master-components/family/<int:aircraft_master_component_family>', launchpad_views.AircraftMasterComponentsFamilyList.as_view(), name='aircraft-master-components-list'),
    path('aircraft-master-components/<uuid:aircraft_master_component_id>', launchpad_views.AircraftMasterComponentsUpdate.as_view(), name='aircraft-master-components-update'),
    path('aircraft-master-components/<uuid:aircraft_master_component_id>/detail', launchpad_views.AircraftMasterComponentsDetail.as_view(), name='aircraft-master-components-detail'),
    path('aircraft-master-components/new', launchpad_views.AircraftMasterComponentsCreateView.as_view(), name='aircraft-master-components-create'),

    path('stock-keeping/<uuid:aircraft_master_component_id>', launchpad_views.AircraftMasterComponentsStockDetail.as_view(), name='aircraft-master-components-stock-keeping'),
    path('stock-keeping', launchpad_views.AircraftMasterComponentsStockDetail.as_view(), name='aircraft-master-components-stock-keeping'),
  
    path('aircraft-components/<uuid:aircraft_component_id>', launchpad_views.AircraftComponentsUpdate.as_view(), name='aircraft-components-update'),
    path('aircraft-components/<uuid:aircraft_component_id>/detail', launchpad_views.AircraftComponentsDetail.as_view(), name='aircraft-components-detail'),
    path('aircraft-components/<uuid:aircraft_component_id>/remove', launchpad_views.AircraftComponentsRemove.as_view(), name='aircraft-components-remove'),
    path('aircraft-components/<uuid:aircraft_master_component_id>/new', launchpad_views.AircraftComponentsCreateView.as_view(), name='aircraft-components-create'),
    path('aircraft-components/verify', launchpad_views.AircraftComponentsSearchView.as_view(), name='verify-aircraft-components'),
    path('aircraft-components/<str:aerobridge_id>/history', launchpad_views.AircraftComponentsHistoryView.as_view(), name='aircraft-components-history'),
    path("aircraft-components/search/", launchpad_views.AircraftComponentsSearchResultsView.as_view(), name="aircraft-components-search-results"),
    path('aircraft-components/<str:view_type>', launchpad_views.AircraftComponentsList.as_view(), name='aircraft-components-list-filtered'),    
    path('aircraft-components', launchpad_views.AircraftComponentsList.as_view(), name='aircraft-components-list'),
 
    path('companies', launchpad_views.CompaniesList.as_view(), name='companies-list'),
    path('companies/<uuid:company_id>', launchpad_views.CompaniesUpdate.as_view(), name='companies-update'),
    path('companies/<uuid:company_id>/detail', launchpad_views.CompaniesDetail.as_view(), name='companies-detail'),
    path('companies/new', launchpad_views.CompanyCreateView.as_view(), name='companies-create'),
    
    
    path('firmwares', launchpad_views.FirmwaresList.as_view(), name='firmwares-list'),
    path('firmwares/<uuid:firmware_id>', launchpad_views.FirmwaresUpdate.as_view(), name='firmwares-update'),
    path('firmwares/new', launchpad_views.FirmwareCreateView.as_view(), name='firmwares-create'),
    path('firmwares/<uuid:firmware_id>/detail', launchpad_views.FirmwaresDetail.as_view(), name='firmwares-detail'),
 
    path('flightplans', launchpad_views.FlightPlansList.as_view(), name='flightplans-list'),
    path('flightplans/<uuid:flightplan_id>', launchpad_views.FlightPlansUpdate.as_view(), name='flightplans-update'),
    path('flightplans/<uuid:flightplan_id>/detail', launchpad_views.FlightPlansDetail.as_view(), name='flightplans-detail'),
    path('flightplans/new', launchpad_views.FlightPlanCreateView.as_view(), name='flightplans-create'),
  

registry/urls.py
from . import views as registryviews
from django.urls import path

urlpatterns = [

    path('pilots/', registryviews.PilotList.as_view(), name='pilot-list'),
    path('pilots/<uuid:pk>', registryviews.PilotDetail.as_view(), name='pilot-detail'),

    path('activities/', registryviews.ActivityList.as_view(), name='activity-list'),
    path('activities/<uuid:pk>', registryviews.ActivityDetail.as_view(), name='activity-detail'),

    path('aircraft/', registryviews.AircraftList.as_view(), name='aircraft-list'),
    path('aircraft/<uuid:pk>', registryviews.AircraftDetail.as_view(), name='aircraft-detail'),
    path('aircraft/rfm/<str:flight_controller_id>', registryviews.AircraftRFMDetail.as_view(),
         name='aircraft-rfm-detail'),
    path('aircraft/firmware/<str:flight_controller_id>', registryviews.AircraftFirmwareDetail.as_view(),
         name='aircraft-firmware-detail'),
    path('aircraft-component/verify/<str:aerobridge_id>', registryviews.VerifyAerobridgeID.as_view(),
         name='verify-aerobridge-id'),
         
    path('operators/', registryviews.OperatorList.as_view(), name='operator-list'),
    path('operators/<uuid:pk>', registryviews.OperatorDetail.as_view(), name='operator-detail'),
    path('manufacturers/', registryviews.ManufacturerList.as_view(), name='manufacturer-list'),
    path('manufacturers/<uuid:pk>', registryviews.ManufacturerDetail.as_view(), name='manufacturer-detail'),

]

pki_framework/models.py
from django.db import models
import uuid
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _
from registry.models import Aircraft, Company, Operator
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from common.validators import validate_currency_code, validate_url
no_special_characters_regex = RegexValidator(regex=r'^[-, ,_\w]*$', message="No special characters allowed in this field.")


class AerobridgeCredential(models.Model):
    ''' A class to store different tokens used in drone operations '''
    
    KEY_ENVIRONMENT = ((0, _('Operator')),(1, _('Manufacturer')),(2, _('Pilot')),(3, _('RFM')),(4, _('Company')),(5, _('Management Server')),)
    TOKEN_TYPE= ((0, _('Public Key')),(1, _('x509 Digital Certificate')),(2, _('Other')),)
    FILE_EXTENSION = ((0, _('other')),(1, _('jwk')),)
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    name = models.CharField(max_length=100, help_text="Provide a friendly name / description for the type of credential you are storing e.g. eBee Public Key", validators = [no_special_characters_regex,])
    
    token_type = models.IntegerField(choices=TOKEN_TYPE, help_text="Set the type of credential this is, e.g Public / Private Key etc.")
    association = models.IntegerField(choices=KEY_ENVIRONMENT, default = 4, help_text="Set the entity this credential is associated with. The association will be used when calling external servers.")
    token = models.BinaryField()
    
    extension = models.IntegerField(choices=FILE_EXTENSION, help_text="Specify the data format for this credential, if known", default = 0)

    aircraft = models.ForeignKey(Aircraft,blank=True, null=True, on_delete = models.CASCADE)
    manufacturer = models.ForeignKey(Company,blank=True, null=True, on_delete = models.CASCADE, limit_choices_to={'role':1})
    operator = models.ForeignKey(Operator,blank=True, null=True, on_delete = models.CASCADE)
    
    is_active = models.BooleanField(default = True, help_text="Set whether the credential is still active")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        
        if (self.association == 0) and (self.operator is None):
            
            raise ValidationError('Please select a Operator for the Operator Token')
            
        elif self.association in [1] and self.manufacturer is None:
            raise ValidationError('Please select a Manufacturer for the Manufacturer Token')

        elif self.association in [3] and self.aircraft is None:
            raise ValidationError('Please select a Aircraft for the Aircraft Token')
    
    def token_type_verbose(self):
        return dict(AerobridgeCredential.TOKEN_TYPE)[self.token_type]

      
class AerobridgeExternalCredential(models.Model):
    ''' A model for custom firmware '''
    KEY_ENVIRONMENT = ((0, _('Auth Server')),)
    TOKEN_TYPE= ((0, _('Full Chain')),)
    token_type = models.IntegerField(choices=TOKEN_TYPE, help_text="Set the type of credential this is, e.g Public / Private Key etc.")
    association = models.IntegerField(choices=KEY_ENVIRONMENT, default = 4, help_text="Set the entity this credential is associated with. The association will be used when calling external servers.")
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    binary_file_url = models.URLField(help_text="Enter a url from where the credential can be downloaded",validators=[validate_url])
    
    name = models.CharField(max_length=140, help_text="Give it a friendly name e.g. Auth server full chain pem")
    is_active = models.BooleanField(default=False,
                                    help_text="Set if the credential is active, don't forget to mark old credentials as inactive")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.version

    def __str__(self):
        return self.version

launchpad/templates/launchpad/credential/credential_delete.html
{% extends "launchpad/layout.html" %} 
{% load rest_framework %}
{% block content %}
<div>
<h1>Credential Storate - {{ credential.token_type }}</h1>

<form action="{% url 'credentials-detail' credentials_id=credentials.pk %}" method="POST">
    {% csrf_token %}
    {% render_form serializer %}
    
    <button  class="btn btn-primary" type="submit" value="Update">Update</button>
    <a href="{% url 'snippet-detail' pk=queryset.pk %}" methods="delete">delete</a>
</form>
</div>
{% endblock %}

launchpad/templates/launchpad/credential/credential_detail.html
{% extends "launchpad/layout.html" %} 
{% load rest_framework %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        Credentials
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        Aerobridge Credential
      </li>
    </ol>
  </nav>
<div>
<h1>Credential Detail - {{ serializer.name }}</h1>
<br>
<table  class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tr>
        <td>Name</td>
        <td><pre>{{serializer.name }}</pre></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><pre>{{serializer.token_type }}</pre></td>
    </tr>
    <tr>
        <td>Is Active</td>
        <td>{{ serializer.is_active}}</td>    
    </tr>
    <tr>
        <td>Association</td>
        <!-- <td>{{ credential.get_association_display }}</td> -->
        <td>{{ serializer.association }}</td>
    </tr>
    
    
</table>
<br>
<p class="text-muted">Created at - {{serializer.created_at}} </p>
<br>
<p><a class="btn btn-primary" href="/launchpad/credentials/{{serializer.id}}"><b>Update Details</b></a></p>

</div>
{% endblock %}

launchpad/templates/launchpad/credential/credential_list.html
{% extends "launchpad/layout.html" %} 
{% block navbreadcrumb %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        Credentials
      </li>
      <li class="breadcrumb-item active" aria-current="page">
        All
      </li>
    </ol>
  </nav>
{% endblock %}
{% block content %}

<div class="row mb-3">
    
    <h2>Credentials</h2>
    <p>You can store credentials, keys for the drone, Digital Sky or other services here. </p>
</div>
<div class="row mb-3">
    <div class="col-md-8 themed-grid-col">

    <ul class="list-group list-group-flush">
        <ul class="list-group list-group-flush">
        {% if credentials.results %}
            {% for credential in credentials.results %}
            <li class="list-group-item"><a href="/launchpad/credentials/{{credential.id}}/detail">{{ credential.association }} - {{ credential.name }}</a>&nbsp;&nbsp;<small class="text-muted">&mdash; Created on {{ credential.created_at }} </small></li>
            {% endfor %}
        {% else %}
            <li class="list-group-item"><p class="text-muted"><i>There are no credentials added in Aerobridge, once added the list of credentials will be displayed here.</i></p></li>
        {% endif %}

    </ul>
    <br>
    
    <br>
    <nav aria-label="Page navigation example">
      <ul class="pagination">
          {% if credentials.links.previous %}
          
          <li class="page-item">
            <a class="page-link" href="{{ credentials.links.previous }}">Previous</a>
          </li>  
            
          {% else %}
            <li class="page-item disabled">
              <a class="page-link">Previous</a>
            </li>
          {% endif %}
          &nbsp;&nbsp;
          {% if credentials.pages %}  
          <li class="page-item" aria-current="page">
            
            <small>Page  {{credentials.page}} of {{ credentials.pages }} </small>
          </li>        
              <small></small>
          {% endif %}
          &nbsp;&nbsp;
          {% if credentials.links.next %}   
          <li class="page-item">
            <a class="page-link" href="{{ credentials.links.next }}">Next</a>
          </li>         
          
          {% else %}
          <li class="page-item disabled">
            <a class="page-link">Next</a>
          </li>
          {% endif %}
      </ul>
    </nav>
    <br>
    <p>&nbsp;</p>
    <p><a class="btn btn-primary" href="/launchpad/credentials/new"><b>&#43; Add a Credential</b></a></p>

</div>
<div class="col-md-4 themed-grid-col"></div>
</div>
{% endblock %}

launchpad/templates/launchpad/credential/credential_update.html
{% extends "launchpad/layout.html" %} 
{% load rest_framework %}
{% block content %}
<div class="row mb-3">
    <div class="col-md-8 themed-grid-col">
<h1>Credential Storage - {{ credential.token_type_verbose }}</h1>
<br>
<p>You can only change credential name, association and set if the credential is still active. You cannot change the credential itself</p>
<br>
<form action="{% url 'credentials-update' credential_id=credential.pk %}" method="POST">
    {% csrf_token %}
    {% if errors %}

        {% for err, val in errors.items %}
            {% for v in val %}
                <p class="alert alert-danger" role="alert">{{err }} : {{ v }}</p><br>
            {% endfor %}
        {% endfor %}
            
    {% endif %}
    {% render_form serializer %}
    <br>
    
    <br>
    <br>
    <button class="btn btn-primary" type="submit" value="Update">Update</button> &nbsp;&nbsp;<a class="btn btn-secondary" href="{% url 'credentials-list' %}" role="button">Cancel</a>
</form>

<br>

</div>
</div>
{% endblock %}

launchpad/templates/launchpad/credential/credentials_create.html
{% extends "launchpad/layout.html" %}
{% load rest_framework %}
{% block content %}
{% load crispy_forms_tags %}
<div class="row mb-3">
    <div class="col-md-8 themed-grid-col">


        <h2>Add a Credential</h2>
        <p>Create a new credential in the database, credentials can be used to sign data, interact with other services.</p>
        <form action="" method="post">
            {% csrf_token %}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            {% crispy form %}
        </form>
    </div>
    <div class="col-md-6 themed-grid-col"></div>
</div>
{% endblock %}

launchpad/templates/launchpad/credential/credentials_read_first.html
{% extends "launchpad/layout.html" %}
{% load rest_framework %}
{% load static %}
{% block content %}
<div class="row mb-3">
    <h2>Get started with Credentials</h2><p> Proceed cautiously, if you dont know what you are doing, Stop! </p>
    <p>While public key cryptography is a well documented area of computing, we assume that you know the basics and understand the risks associated with storing keys on a public facing server. If you dont, get a professional to review / understand the implications. </p><p>While Aerobridge stores the keys with simple security which should suffice for simpler non-production applications. For production use, we recommend using a system such as <a href="https://www.hashicorp.com/products/vault">Hashicorp Vault</a> to store / manage secrets, we can help you with the setup, see the contact form below:</p><br><br>
</div>
<div class="row mb-3">
    <ol class="list-group list-group-numbered">
        <li class="list-group-item">Create a public / private key for you any pilot / operator</li>
        <li class="list-group-item">You can use a following commands to create a public / private key pair.<br><br>
            <code>
            ssh-keygen -t rsa -b 4096 -m PEM -f operator.key
        </code><br><code>
            openssl rsa -in operator.key -pubout -outform PEM -out operator.key.pub

        </code><br><br>
        </li>     
        <li class="list-group-item">The above code will generate a public key in PEM format and a private key <mark>operator.key</mark>. These are confidential files and can then be stored in Aerobridge via the <a href="/launchpad/credentials">Credentials Manager</a>. Private keys should not be stored in the server, unless it is accompanied by a system like Vault.</li>           
    </ol>
</div>
{% endblock %}